name: go-pr-commenter release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: releasing go-pr-commenter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          stable: 'false'
          go-version: '1.18'
      - run: go version

      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
